### PR TITLE
PLUGIN-1588: Make auth optional for Confluent Streaming Sink

### PR DESCRIPTION
**Pull request by sgarg-CS**
[PLUGIN-1588](https://cdap.atlassian.net/browse/PLUGIN-1588)

### CODE REVIEW

**Review by greeshmaswaminathan — COMMENTED** [review]
Code LGTM. Can you add unit tests ?

**Comment by sgarg-CS** [comment]
> Code LGTM. Can you add unit tests ?

Added. fa08e1d4d10b32e0860f2f584b3b6af7d8d56590

**Review by greeshmaswaminathan — APPROVED** [review]

**Review by greeshmaswaminathan — COMMENTED** [review]
Please squash the commits before merge.

**Comment by sgarg-CS** [comment]
Commits have been squashed. 4ad9e470262d436893e9593948d99aeab8028823

**Pull request merged**
